version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: ProductDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

 
  examplewebapi:
    image: ${DOCKER_REGISTRY-}examplewebapi
    build:
      context: .
      dockerfile: ExampleWebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ProductDb;Username=postgres;Password=postgrespassword
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5000:8081"
    depends_on:
      - postgres
    networks:
      - app-network
 

volumes:
  postgres-data:
